export let config = {
    "token": "NTU5MDE1OTA2OTY2MjQxMjkx.XMFxWQ.xxojAj95p6gF8l1gdS9Cmw2a_so",
    "prefix": "!",
    "commands": [
        "purge",
        "testCommand",
        "kick",
        "ban",
        "info", 
        "poll",
        "av",
        "money",
        "buy",
        "bc",
        "clear",
        "help",
        "mute",
        "nick",
        "greg",
        "inv",
        "gamble",
        "fuck",
        "kiss",
        "unfuck",
        "rukh",
        "sol",
        "pat",
        "highfive",
        "hug",
        "lick",
        "poke",
        "insult",
        "greet",
        "wave",
        "stare",
        "ship",
        "addmoney",
        "removemoney",
        "cuddle",
        "embed",
        "pay",
        "set",
        "hydra",
        "uptime",
        "vanya",
    ]
}